### ISSUE TITLE
Flows Service is down !

### ISSUE THREAD

**Issue by thefrench2005** [savonet/flows-push#2]
http://flows.liquidsoap.fm/ is working but no radio registered and i can't retrieve any information from queries to the service (service is down for more than 24 hours)

**Comment by smimram** [comment]
@toots is the guy who knows about flows, let's wait for his answer...

**Comment by toots** [comment]
Seems to be working, at least at the moment. @thefrench2005: Can you confirm? (nice nick btw!)

**Comment by thefrench2005** [comment]
Yes it's working again. (I really need it to work because i'm using it on my webradio website and widgets in order to display current title)
Thanks a lot !

**Comment by smimram** [comment]
It's nice to see flows used! Out of curiosity, what is your webradio (if it is publicly available)?

**Comment by thefrench2005** [comment]
Sure it's publicly available for 3 years now ! Here is the link : http://www.frequenceorange.com (it's french). Any feedback appreciated
